version: '3'
services:
  db:
    image: mysql:8.0.29
    restart: on-failure
    platform: linux/x86_64
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=trybecashdb
    ports:
      - 33060:3306